# from dust i have come, dust i will be

import xlrd
import xlwt

# the following file is generated by sunshine_analysis.py
location = "E:\Programming\experimenting-api\wre_thesis_code\Rainfall_avg.xls"

wb = xlrd.open_workbook(location)
sheet = wb.sheet_by_index(0)

# extracting number of rows
row = sheet.nrows

# extracting number of columns
col = sheet.ncols

output = xlwt.Workbook()
output_sheet = output.add_sheet("10_year_rainfall")

'''
task : for district -> Comilla, Feni, Chandpur
find 10y average for each month from 
1981-1990
1990-2000
1991-2010

district -> month -> 3 tens
'''

output_sheet.write(0, 0, "District")
output_sheet.write(0, 1, "Month")
output_sheet.write(0, 2, "Year-Range")
output_sheet.write(0, 3, "Avg Rainfall")

districts = {'Comilla': 0, 'Feni': 1, 'Chandpur': 2}

data = [[[0 for k in range(3)] for j in range(12)] for i in range(3)]
cnt = [[[0 for z in range(3)] for y in range(12)] for x in range(3)]

for i in range(1, row):
    district = sheet.cell_value(i, 0)
    year = int(sheet.cell_value(i, 1))
    month = int(sheet.cell_value(i, 2))
    avg = float(sheet.cell_value(i, 3))

    d = districts[district]
    month -= 1

    if 1981 <= year <= 1990:
        y = 0
    elif 1991 <= year <= 2000:
        y = 1
    else:
        y = 2

    # in case of rainfall always add the avg
    # i.e. remove the if and keep the 2 statements under the if
    # if avg > 0.0:
    data[d][month][y] += avg
    cnt[d][month][y] += 1

last_row_written = 0

year_range = ["1981-1990", "1991-2000", "2001-2010"]
district_name = ["Comilla", "Feni", "Chandpur"]

for i in range(3):
    for j in range(12):
        for k in range(3):
            if cnt[i][j][k]:
                data[i][j][k] /= cnt[i][j][k]
            else:
                data[i][j][k] = 0.0

            data[i][j][k] = round(data[i][j][k], 3)

            last_row_written += 1
            output_sheet.write(last_row_written, 0, district_name[i])
            output_sheet.write(last_row_written, 1, str(j + 1))
            output_sheet.write(last_row_written, 2, year_range[k])
            output_sheet.write(last_row_written, 3, str(data[i][j][k]))


output.save("ten_year_rainfall_avg.xls")
